export const aboutButton = document.getElementById("about")
export const workButton = document.getElementById("works")
export const sourceButton = document.getElementById("source")
export const closeButton = document.getElementById("close")
export const popup = document.getElementById("popup")
export const home = document.getElementById("home")
export const titlePopUp = document.getElementById("title")
export const subTitlePopUp = document.getElementById("subTitle")
export const paragraphPopUp = document.getElementById("paragraph")
export const soucerTitle = document.getElementById("sourcer")
export const platformTitle = document.getElementById("platform")
export const stackTitle = document.getElementById("stack")
export const containerWork = document.getElementById("works-container")

